# Generated by Django 4.0.2 on 2022-07-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproduct_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
    ]
